name: CI
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------------------

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # ------------------------------------------------------------------------

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      # ------------------------------------------------------------------------

      - name: Setup Python
        uses: actions/setup-node@v4
        with:
          python-version: '3.11'
      - run: python -m pip install -r requirements.txt

      # ------------------------------------------------------------------------

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install

      # ------------------------------------------------------------------------
