name: push_main
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TARGET_ARCHITECTURE: x64
    steps:
      # ------------------------------------------------------------------------

      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive